### ISSUE TITLE
C/C++ code status

### ISSUE THREAD

**Issue by renatosc** [paulvangentcom/heartrate_analysis_python#10]
I read somewhere (maybe in the tutorials?) that you would be porting this code to c/c++. What is the status of that?

**Comment by paulvangentcom** [comment]
As of now it's halfway through but on ice. I've ported most numerical portions to numpy/scipy methods which rely on C++ methods and are thus already very fast.

An intermediate is available on the arduino heartbeat repo for now: https://github.com/paulvangentcom/heartrate_analysis_Arduino

Docs: https://embedded-heart-rate-analysis-toolkit.readthedocs.io/en/latest/

It's a general repo of various versions, from just recording data and auto-scaling, to various on-line analysis implementations. But, here I need to to a lot of refactoring, optimization and tweaking of the peak finding robustness still. This is what will take my attention over the coming weeks.

After I push those changes, porting to a general C/C++ package is a smaller step. I'll keep you updated when I start on that, maybe you can help as well!
