### ISSUE TITLE
Visualisation of rejected RR values 

### ISSUE THREAD

**Issue by FrancoisCosta** [paulvangentcom/heartrate_analysis_python#20]
Hey!

It would be super useful to be able to visualise the rejected RR-interval values (RR_list_cor) on the graph - to make sure that the intervals are being correctly rejected and for other troubleshooting issues. 

Is there a function for this in the code? I couldn't find one..

Thanks! :)

**Comment by paulvangentcom** [comment]
RR-intervals are only computed between two non-rejected peaks, as long as there is no rejected peak in between. Further, in the final step peaks are rejected if they exceed thresholds as defined in `check_peaks()`, being that two adjacent peaks create an RR-interval larger than `mean RR + 30%` with a minimum of 300ms. 

Visualising rejected RR-intervals would not add any information to the plot as this is all contained in the rejected peaks, which are visualised already.

-Paul
