### ISSUE TITLE
AVR simple logger with scaling + python peak detection 

### ISSUE THREAD

**Issue by FrancoisCosta** [paulvangentcom/heartrate_analysis_python#21]
Hi Paul,

I've implemented the AVR simple logger with scaling with my Arduino UNO this morning.
I then used this python toolbox for peak detection (the Arduino version is limited to 250Hz whereas I am sampling at 1000Hz for 1ms RR-interval precision). The scaler-peak detection combination seems to work perfectly until it encounters some noise. I've tried to illustrate this with the pictures below:

![first_100k_samples](https://user-images.githubusercontent.com/39350856/55719392-0c051f80-59f6-11e9-945e-88f0236a045e.png)

This represents the first 100k data entries (sampled at 1kHz). Peak detection working perfectly!

![first_110k_samples](https://user-images.githubusercontent.com/39350856/55719394-0c9db600-59f6-11e9-9cbd-5255cecb0d38.png)

At approx ~110k samples, the sensor encounters a little bit of noise (probably due to movement) leading to two problems:
--> The systolic and diastolic are both detected - doubling the heart rate
-->As a result the RR intervals are incorrect

My understanding is that this happens because, following the noise, the moving average moves below the diastolic peaks. 

![first_200k_samples](https://user-images.githubusercontent.com/39350856/55719395-0c9db600-59f6-11e9-9b3d-03deda4e68cf.png)

Graph showing the first 200k samples, with the noise @110k. 

Here's my data file:

[sensor_scaled_data.txt](https://github.com/paulvangentcom/heartrate_analysis_python/files/3054000/sensor_scaled_data.txt)

**Comment by paulvangentcom** [comment]
Hi Francois,

That is something that sometimes happens yeah. I'm still chewing on a possible solution.

For now you can try suppressing the diastolic peaks with the built-in filter method, like so:

```python
import heartpy as hp

data = hp.get_data('sensor_scaled_data.txt')

#filter with a low-pass butterworth, cutoff > 3.5 Hz (>120 bpm), third order
filt = hp.filtersignal(data, cutoff=3.5, sample_rate=1000.0, order=3, filtertype='lowpass')
#scale the data afterwards to be sure, not always necessary
filt_scaled = hp.scale_data(f)

wd, m = hp.process(filt_scaled, 1000.0)
hp.plotter(wd, m)
```

This gives:
![issue21_1](https://user-images.githubusercontent.com/15799488/55747276-2a8e0980-5a3c-11e9-8676-164996f4dbb2.jpeg)

Zooming in on the troubled area:
![issue21_2](https://user-images.githubusercontent.com/15799488/55747286-311c8100-5a3c-11e9-8e6d-acf916194f5c.jpeg)

Once I have a handle on how to handle these situations properly, I suspect with an extra peak rejection round, I'll let you know. For now this is a workaround
