### ISSUE TITLE
Customize the plotter window length

### ISSUE THREAD

**Issue by PartyTrix** [paulvangentcom/heartrate_analysis_python#26]
If you add to the plotter function a parameter `length = 6` and the corresponding `plt.figure(figsize=(length ,6))` to the function, one can dynamically adjust the length of the resulting pyplot (for example:  `plotter(df,20)` )plot in inches.
Something that might be handy for quickly viewing the result of a larger set.

**Comment by paulvangentcom** [comment]
This is already possible because it uses matplotlib under the hood anyway:

```python
import heartpy as hp
import matplotlib.pyplot as plt

data = hp.get_data('data.csv')
wd, m = hp.process(data, sample_rate=100.0)

plt.figure(figsize=(12,12))
hp.plotter(wd, m) #this will draw a 12x12 plot as requested. 
#You can of course also use show=False and then save to a file.

```
