### ISSUE TITLE
interpolating clipping while using process_segmentwise

### ISSUE THREAD

**Issue by FrancoisCosta** [paulvangentcom/heartrate_analysis_python#27]
Hi Paul,

Is there a way of interpolating clipping while using 
`process_segmentwise(data)
` 

I know it's possible when using proces sby setting
` process(data,interp_clipping=False)`

Cheers,
Francois

**Comment by paulvangentcom** [comment]
[Per the docs you can](https://python-heart-rate-analysis-toolkit.readthedocs.io/en/latest/quickstart.html#getting-heart-rate-over-time):

" you can pass all the arguments normally passed to the process() function at the end of the arguments here as well. These will be passed on and used in the analysis."

Good luck!
