### ISSUE TITLE
error

### ISSUE THREAD

**Issue by abdulkhaliq7** [paulvangentcom/heartrate_analysis_python#34]
hi, I was doing Analysing a Noisy ECG Signal but when i run the code below I'm getting the error
"AttributeError: module 'HeartPy' has no attribute 'enhance_ecg_peaks'"....can u help me with it

filtered =hp.enhance_ecg_peaks(hp.scale_data(ecg), sample_rate, 
                                aggregation='median', iterations=5)

#show filtered signal
plt.figure(figsize=(12,4))
plt.plot(filtered)
plt.show()

#zoom in on signal section and overlay filtered segment 
plt.figure(figsize=(12,4))
plt.title('original signal zoom in')
plt.plot(hp.scale_data(ecg[15000:17000]), label='original data')
plt.title('processed signal zoom in')
plt.plot(hp.scale_data(filtered[15000:17000]), alpha=0.5, label='processed data')
plt.legend()
plt.show()

**Comment by paulvangentcom** [comment]
Sounds like you're using an older version of HeartPy, from before enhance_ecg_peaks was implemented.

You need to install the latest version from the github using the setup.py file. Clone or download the repository, and do:

```
python -m setup.py install
```

**Comment by abdulkhaliq7** [comment]
thnks
