### ISSUE TITLE
attribute missing

### ISSUE THREAD

**Issue by abdulkhaliq7** [paulvangentcom/heartrate_analysis_python#35]
hi, I have downloaded the latest version=1.2.4 of  heartpy package  and still I'm getting this error:

 filtered = hp.enhance_ecg_peaks(hp.scale_data(ecg), sample_rate, iterations=4, aggregation='median', notch_filter=True)

AttributeError: module 'HeartPy' has no attribute 'enhance_ecg_peaks

I  appreciate your help!!!!😄

**Comment by paulvangentcom** [comment]
Make sure you uninstall the older version first prior to installing the new one, it seems you're still not on the newest version..

```pip uninstall -y heartpy```

**Comment by abdulkhaliq7** [comment]
thank u v. much it is working.

I'm doing heart disease detection using deep-learning,,,how do I download MIT-BIH arrhythmia database and loaded with the wfdb package......and is the heartpy support heartbeat segmentation and feature extraction. 

thanks in advance.
