### ISSUE TITLE
Welch and periodogram methods in calc_fd_measures

### ISSUE THREAD

**Issue by ftsarhaddi** [paulvangentcom/heartrate_analysis_python#48]
Hi,
In calc_fd_measures, if using welch or periodogram method, it is needed to add dx = freq[1]-freq[0] parameters for np.trapz function for calculating HF and LF. It works for fft since you divide fft by datalen.

**Comment by AndrewDDavis** [comment]
Yes, the values coming from the fd measures were not close to the accepted values in the literature. I have reworked that section and put in a [pull request](https://github.com/paulvangentcom/heartrate_analysis_python/pull/55).

**Comment by paulvangentcom** [comment]
Thanks for noticing @ftsarhaddi, and thanks for the swift implementation @AndrewDDavis. I've merged your pr #55, which resolves this issue nicely
