### ISSUE TITLE
Frequency Analysis Result

### ISSUE THREAD

**Issue by iPsych** [paulvangentcom/heartrate_analysis_python#49]
First, I sincerely appreciate for the properly working BVP/ECG analysis codes you shared.
I have a question about the frequency domain result.
When I try to analyze BVP data with very long length (>3hrs),
The result shows EXTREAMLY large value for hf and lf power (line 44).
But the lf/hf makes sense, and the value is reasonable if I divide it by 1000^2 (maybe for ms^2).
Would you let me know what is the unit of raw HF, LF and is it correct to divide it by 1000^2 for get the trivial ms^2 result?
![PastedGraphic-1](https://user-images.githubusercontent.com/28276515/92339137-907a3700-f0ef-11ea-8c54-735416647d62.png)

**Comment by paulvangentcom** [comment]
The result is raw area-under-curve for the frequency range, so you need to transform it into your desired metric such as ms^2

Hope this helps

Cheers
Paul

**Comment by iPsych** [comment]
@paulvangentcom 
Thanks. I am little confused what 'raw area-under-curve for the frequency range' means.
So, to convert ms^2 metric, should I divide it with (1000*1000)? Or the equation should be changed based on my sampling rate?
