### ISSUE TITLE
plot_poincare() method error

### ISSUE THREAD

**Issue by Franziska-L** [paulvangentcom/heartrate_analysis_python#57]
I'm getting an error when I try to call the method plot_poincare(): "alpha must be a float or None".
This error also occurs in the examples like 2_regular_ECG and 5_noisy_ECG of the Github page.

Issue #44 seems to have fixed this but I still get the error.
My HeartPy Version is 1.2.6

**Comment by paulvangentcom** [comment]
Try uninstalling first

```pip uninstall heartpy```, then cloning the repo and running ```python setup.py install```

The pip release is a bit behind, it's on my radar to fix. Of course feel free to let me know if the problem persists. 

Cheers

**Comment by Franziska-L** [comment]
Thanks. Poincare_plot() is working now but I get another error: `UserWarning: Matplotlib is currently using module://ipykernel.pylab.backend_inline, which is a non-GUI backend, so cannot show the figure.`

I'm using Python 3.7 since 2.7 is deprecated.

**Comment by paulvangentcom** [comment]
This error has to do with Jupyter Notebook and not HeartPy.

Try adding ```%matplotlib inline``` to the notebook cell where you do the imports.

If that doesn't work, have a look at the suggestions here https://stackoverflow.com/questions/37365357/when-i-use-matplotlib-in-jupyter-notebook-it-always-raise-matplotlib-is-curren

Cheers

**Comment by paulvangentcom** [comment]
I'm closing this for now. Feel free to reopen or open another issue if you encounter further problems!

Cheers
Paul
