### ISSUE TITLE
AttributeError: module 'HeartPy' has no attribute 'heart_rates'

### ISSUE THREAD

**Issue by Sorcha19** [paulvangentcom/heartrate_analysis_python#67]
won't allow you change load_example_data to your own
<img width="932" alt="Screenshot 2021-04-19 at 12 33 10" src="https://user-images.githubusercontent.com/32652073/115229855-7552b980-a10b-11eb-8f2b-6556a59837c0.png">

**Comment by paulvangentcom** [comment]
There's a built in function to open CSV or MAT files, [see the docs here]( Connection activation failed: Could not find source connection.). 

However, in most cases you can just load your data into a list or array and pass that to heartpy.

-Paul
