### ISSUE TITLE
Calculation of SPo2

### ISSUE THREAD

**Issue by mshafieluru** [paulvangentcom/heartrate_analysis_python#68]
Hi

I request you to let me know 

a) if it is possible to calculate SPo2 values using the data and example mentioned in 

https://github.com/paulvangentcom/heartrate_analysis_python/blob/master/examples/3_smartwatch_data/Analysing_Smartwatch_Data.ipynb

Please let me know how to achieve it.

b) in your opinion what is the optimal sampling rate and for how many seconds of data should be captured from a wearable wristband.

Regards
Shafi

**Comment by paulvangentcom** [comment]
Hi Shafi,

a. I haven't looked into SpO2 extraction, but I believe it should be possible. I'll put it on the to-do but cannot promise anything, as my time is limited at the moment.

b. The more the better, basically. 100Hz is good already, but in the past I've worked as low as 10Hz as well, although for HRV metrics it's better to be higher in the spectrum.

Cheers,
Paul
