### ISSUE TITLE
Comparison of Raw vs Clean signal?

### ISSUE THREAD

**Issue by darpitdavetamu** [paulvangentcom/heartrate_analysis_python#69]
I am using HeartPy to extract features from ECG signal using heartpy.process function.

I wanted to graphically compare the raw signal vs the processed signal (output of process function) that is used for peak detection.

Where can I find this output stored?

**Comment by paulvangentcom** [comment]
the process function outputs detected RR-peaks and metrics. 

The signal used is buffered in working_data['hr'], assuming you run the process function as ```wd, m = hp.process(...)```

cheers
