### ISSUE TITLE
What units is the raw PPG data in? 

### ISSUE THREAD

**Issue by melissamullen** [paulvangentcom/heartrate_analysis_python#74]
Looks way too high to be the standard BPM...

Our data is in BPM and we are getting the following error when running the process method (note that we have resampled and filtered our smartwatch data as you did in the example). Could it be because the units aren't the same as yours?

```
----------------
Could not determine best fit for given signal. Please check the source signal.
 Probable causes:
- detected heart rate falls outside of bpmmin<->bpmmax constraints
- no detectable heart rate present in signal
- very noisy signal (consider filtering and scaling)
If you're sure the signal contains heartrate data, consider filtering and/or scaling first.
----------------
```

**Comment by paulvangentcom** [comment]
Hi Melissa,

The standard PPG data unit is the sensor value at a moment in time. If you have your data in BPM, that is typically already too processed for HeartPy to make sense of.

Paul

**Comment by paulvangentcom** [comment]
closing for now, feel free to re-open if there are further questions
