### ISSUE TITLE
Hi Sreehari, how can i import heartbeat_audio_experimental in python

### ISSUE THREAD

**Issue by Ayude** [paulvangentcom/heartrate_analysis_python#8]
Hi Sreehari,

Apologies for the delay, I broke my thumb earlier so I've not had much coding time available.

I've pushed an experimental function to the repo (in the folder 'experimental'). Please be aware that the peak detection is not super accurate yet and will be thrown off if there's a lot of noise. 

Since the variability measures are noise-sensitive they should **not** be trusted. The BPM value as you requested, however, is much more noise-resistant and should be a pretty good estimate of the real BPM in the audio file (given there is not too much noise).

Usage is similar to the main module:

```
import heartbeat_audio_experimental as hb_audio

measures = hb_audio.process('heartbeat.wav')
print(measures['bpm'])
hb_audio.plotter()
```

This gives:

![plotter output](http://www.paulvangent.com/files/audio_plot.jpeg)

Let me know if this helps your project.

- Paul van Gent

_Originally posted by @paulvangentcom in https://github.com/paulvangentcom/heartrate_analysis_python/issues/2#issuecomment-351683949_

**Comment by paulvangentcom** [comment]
I have re-uploaded the experimental file.

Please note that it is a quick hack, and I cannot guarantee functionality until I have time to develop it further. For now the functionality is not planned in the short term.
