### ISSUE TITLE
hp.process issue when running on Thonny

### ISSUE THREAD

**Issue by kamilah2520** [paulvangentcom/heartrate_analysis_python#81]
When it compiles the code I wrote works fine, until executes the hp.process() function; generates an error with Thonny's back-end, which I don't understand what it means. I want to use this toolkit to obtain BPM from an array generated from a photo transceiver I created as a HR Sensor replacement. I'm working on my Raspi3 by the way, on Raspbian.
`ERROR   thonny.backend: PROBLEM WITH THONNY'S BACK-END
Traceback`

**Comment by paulvangentcom** [comment]
Can you share with me the full traceback message?
