### ISSUE TITLE
What "s" stand for?

### ISSUE THREAD

**Issue by BaggioMarco** [paulvangentcom/heartrate_analysis_python#89]
Hi,

thank you so much for this great pack!
I'm just wondering which is the meaning of "s" that is listed among the other indices.
It get printed by this block below:

```
#display measures computed
for measure in m.keys():
    print('%s: %f' %(measure, m[measure]))
```

thanks in advance

**Comment by paulvangentcom** [comment]
It's a component of the poincare analysis. 

Consider this snippet of code:

```python
import heartpy as hp

data, _ = hp.load_exampledata(2)
wd, m = hp.process(data, sample_rate = 100.0, high_precision = True)
hp.plot_poincare(wd, m)
```

This gives the following plot:
![poincareplot](https://user-images.githubusercontent.com/15799488/146320012-82b469e8-3bf5-475d-93de-3897f63ffe03.jpeg)

This plots the peak-peak intervals with RR(n) on the x-axis and RR(n+1) on the Y axis.

SD1 is the standard deviation of intervals along the identity line (x=y)
SD2 is the standard deviation of intervals perpendicular to the identity line
S is the *surface area* of the ellipsoid described by SD1 and SD2

Hope this answers your question :)

Cheers

**Comment by paulvangentcom** [comment]
Closing for now. Feel free to re-open if you have additional questions or comments
